<script setup lang="ts">
import type { TableColumn } from '@nuxt/ui'
definePageMeta({ layout: 'dashboard' })
type ScoreKey = 'workAlignmentScore' | 'workScopeScore' | 'learningOpportunityScore' | 'supervisorReadinessScore' | 'studentSupportScore' | 'environmentScore' | 'safetyScore' | 'resourcesScore' | 'welfareScore' | 'travelScore' | 'transportScore' | 'accommodationScore' | 'coordinationScore'
type Evaluation = Record<ScoreKey, number | null> & { status: 'DRAFT' | 'SUBMITTED', observations: string | null, companyNeeds: string | null, problems: string | null, recommendations: string | null, futureRecommendation: string | null }
interface Item { appointmentId: number, appointmentStatus: 'PUBLISHED' | 'RESCHEDULED' | 'COMPLETED', companyName: string, groupName: string, roundNo: number, cycle: { term: number, academicYear: number }, evaluation: Evaluation | null }
const { data: items, status, error, refresh } = await useFetch<Item[]>('/api/teacher/company-evaluations')
const notify = useNotify(); const search = ref(''); const selected = ref<Item | null>(null); const open = ref(false); const saving = ref(false)
const scoreLabels: Array<{ key: ScoreKey, label: string }> = [{ key: 'workAlignmentScore', label: 'ความสอดคล้องของงานกับสาขา' }, { key: 'workScopeScore', label: 'ขอบเขตและความท้าทายของงาน' }, { key: 'learningOpportunityScore', label: 'โอกาสเรียนรู้และพัฒนาทักษะ' }, { key: 'supervisorReadinessScore', label: 'ความพร้อมของผู้ควบคุมงาน' }, { key: 'studentSupportScore', label: 'การดูแลและช่วยเหลือนักศึกษา' }, { key: 'environmentScore', label: 'สภาพแวดล้อมในการทำงาน' }, { key: 'safetyScore', label: 'ความปลอดภัยและสุขอนามัย' }, { key: 'resourcesScore', label: 'อุปกรณ์และทรัพยากร' }, { key: 'welfareScore', label: 'สวัสดิการ/ค่าตอบแทน' }, { key: 'travelScore', label: 'ความสะดวกและปลอดภัยในการเดินทาง' }, { key: 'transportScore', label: 'การเข้าถึงขนส่งสาธารณะ' }, { key: 'accommodationScore', label: 'ความเหมาะสมของที่พัก' }, { key: 'coordinationScore', label: 'การประสานงานกับมหาวิทยาลัย' }]
const form = reactive<Record<ScoreKey | 'observations' | 'companyNeeds' | 'problems' | 'recommendations' | 'futureRecommendation', number | null | string>>(Object.fromEntries([...scoreLabels.map(x => [x.key, null]), ['observations', ''], ['companyNeeds', ''], ['problems', ''], ['recommendations', ''], ['futureRecommendation', '']]) as any)
const state = (item: Item) => item.appointmentStatus !== 'COMPLETED' ? 'WAITING' : item.evaluation?.status ?? 'NOT_STARTED'
const info = (item: Item) => ({ WAITING: { label: 'รอนิเทศเสร็จ', color: 'neutral' as const }, NOT_STARTED: { label: 'ยังไม่เริ่มประเมิน', color: 'warning' as const }, DRAFT: { label: 'กำลังประเมิน', color: 'info' as const }, SUBMITTED: { label: 'ประเมินครบแล้ว', color: 'success' as const } }[state(item)])
const filtered = computed(() => (items.value ?? []).filter(x => !search.value || [x.companyName, x.groupName, x.appointmentId].join(' ').toLowerCase().includes(search.value.trim().toLowerCase())))
const edit = (item: Item) => { selected.value = item; scoreLabels.forEach(x => form[x.key] = item.evaluation?.[x.key] ?? null); (['observations', 'companyNeeds', 'problems', 'recommendations', 'futureRecommendation'] as const).forEach(x => form[x] = item.evaluation?.[x] ?? ''); open.value = true }
const setScore = (key: ScoreKey, value: string | number | null) => { form[key] = value === '' || value === null ? null : Number(value) }
const save = async (submit: boolean) => { if (!selected.value) return; saving.value = true; try { await $fetch(`/api/teacher/company-evaluations/${selected.value.appointmentId}`, { method: 'PUT', body: { ...form, submit } }); notify.success(submit ? 'ส่งแบบประเมินเรียบร้อยแล้ว' : 'บันทึกร่างแบบประเมินแล้ว'); open.value = false; await refresh() } catch (err: any) { notify.error(err?.data?.message || err?.message || 'ไม่สามารถบันทึกแบบประเมินได้') } finally { saving.value = false } }
const columns: TableColumn<Item>[] = [{ accessorKey: 'companyName', header: 'สถานประกอบการ' }, { id: 'context', header: 'นัดหมาย / กลุ่ม' }, { id: 'state', header: 'สถานะ' }, { id: 'actions', header: 'จัดการ', meta: { class: { th: 'w-28 text-end', td: 'w-28 text-end' } } }]
</script>
<template><UDashboardPanel id="teacher-company-evaluations"><template #header><UDashboardNavbar title="ประเมินสถานประกอบการ"><template #leading><UDashboardSidebarCollapse /></template><template #right><UIButtonRefresh :loading="status === 'pending'" @refresh="refresh" /></template></UDashboardNavbar></template><template #body><div class="space-y-4 p-4 sm:p-6"><UAlert v-if="error" color="error" title="ไม่สามารถโหลดงานประเมินได้" :description="error.message" /><UInput v-model="search" icon="i-lucide-search" placeholder="ค้นหาบริษัท กลุ่ม หรือนัดหมาย" class="sm:max-w-sm" /><div class="overflow-hidden rounded-lg border border-default bg-default"><UTable :data="filtered" :columns="columns" :loading="status === 'pending'" :ui="{ root: 'overflow-x-auto', base: 'min-w-full' }"><template #context-cell="{ row }">นัดหมาย #{{ row.original.appointmentId }} · {{ row.original.groupName }} · ครั้งที่ {{ row.original.roundNo }}</template><template #state-cell="{ row }"><UBadge :color="info(row.original).color" variant="subtle">{{ info(row.original).label }}</UBadge></template><template #actions-cell="{ row }"><UButton v-if="state(row.original) !== 'WAITING'" :label="state(row.original) === 'SUBMITTED' ? 'ดูผล' : 'ประเมิน'" color="primary" variant="ghost" size="xs" @click="edit(row.original)" /></template><template #empty><div class="py-12 text-center text-muted">ยังไม่มีสถานประกอบการที่อยู่ในรายการนิเทศของคุณ</div></template></UTable></div></div></template></UDashboardPanel><UModal v-model:open="open" :title="selected ? `ประเมิน ${selected.companyName}` : 'ประเมินสถานประกอบการ'"><template #body><div v-if="selected" class="space-y-5"><div v-for="item in scoreLabels" :key="item.key" class="grid gap-2 sm:grid-cols-[1fr_7rem] sm:items-center"><label :for="item.key">{{ item.label }}</label><UInput :id="item.key" type="number" min="1" max="5" :model-value="form[item.key] as number | null" :disabled="selected.evaluation?.status === 'SUBMITTED'" @update:model-value="setScore(item.key, $event)" /></div><UFormField v-for="field in [{ key: 'observations', label: 'ข้อสังเกตจากการนิเทศ' }, { key: 'companyNeeds', label: 'ความต้องการของสถานประกอบการ' }, { key: 'problems', label: 'ปัญหาที่พบ' }, { key: 'recommendations', label: 'ข้อเสนอแนะ' }, { key: 'futureRecommendation', label: 'คำแนะนำสำหรับรุ่นต่อไป' }]" :key="field.key" :label="field.label"><UTextarea v-model="form[field.key as 'observations' | 'companyNeeds' | 'problems' | 'recommendations' | 'futureRecommendation'] as string" :disabled="selected.evaluation?.status === 'SUBMITTED'" /></UFormField></div></template><template #footer><div v-if="selected?.evaluation?.status !== 'SUBMITTED'" class="flex justify-end gap-2"><UButton color="neutral" label="บันทึกร่าง" :loading="saving" @click="save(false)" /><UButton color="primary" label="ส่งแบบประเมิน" :loading="saving" @click="save(true)" /></div></template></UModal></template>
