<script setup lang="ts">
definePageMeta({ layout: 'dashboard' })
type EvaluationType = 'student' | 'company'
interface Cycle { id: number, term: number, academicYear: number, cohortYear: number }
interface Question { id: number, evaluationType: EvaluationType, label: string, scoreKey: string, sortOrder: number, isActive: boolean }
const notify = useNotify(); const { data: cycles } = await useFetch<Cycle[]>('/api/cooperative-cycles'); const selectedCycleId = ref<number>(); const evaluationType = ref<EvaluationType>('student'); const questions = ref<Question[]>([]); const saving = ref(false)
watch(cycles, items => { if (!selectedCycleId.value && items?.[0]) selectedCycleId.value = items[0].id }, { immediate: true })
const options = computed(() => (cycles.value ?? []).map(c => ({ label: `ภาคเรียนที่ ${c.term}/${c.academicYear} · รุ่น ${c.cohortYear}`, value: c.id }))); const current = computed(() => questions.value.filter(q => q.evaluationType === evaluationType.value && q.isActive))
const load = async () => { if (selectedCycleId.value) questions.value = await $fetch<Question[]>(`/api/staff/cooperative-cycles/${selectedCycleId.value}/evaluation-questions`) }
watch([selectedCycleId, evaluationType], load, { immediate: true }); const add = () => questions.value.push({ id: 0, evaluationType: evaluationType.value, label: '', scoreKey: '', sortOrder: current.value.length, isActive: true }); const remove = (q: Question) => { const i = questions.value.indexOf(q); if (i >= 0) questions.value.splice(i, 1) }
const save = async () => { if (!selectedCycleId.value) return; saving.value = true; try { await $fetch(`/api/staff/cooperative-cycles/${selectedCycleId.value}/evaluation-questions`, { method: 'PUT', body: { evaluationType: evaluationType.value, questions: current.value.filter(q => q.label.trim()) } }); await load(); notify.success('บันทึกชุดคำถามเรียบร้อยแล้ว') } catch (e: any) { notify.error(e?.data?.message || 'ไม่สามารถบันทึกชุดคำถามได้') } finally { saving.value = false } }
</script>
<template><UDashboardPanel id="staff-settings-evaluations"><template #header><AppDashboardNavbar title="จัดการการประเมิน" /></template><template #body><div class="space-y-4 p-4 sm:p-6"><UCard><div class="flex flex-wrap items-end justify-between gap-4"><UFormField label="รอบสหกิจศึกษา"><USelect v-model="selectedCycleId" :items="options" value-key="value" size="xl" class="w-72" /></UFormField><div class="flex gap-2"><UButton label="ประเมินนักศึกษา" size="xl" :color="evaluationType === 'student' ? 'primary' : 'neutral'" :variant="evaluationType === 'student' ? 'solid' : 'outline'" @click="evaluationType = 'student'" /><UButton label="ประเมินสถานประกอบการ" size="xl" :color="evaluationType === 'company' ? 'primary' : 'neutral'" :variant="evaluationType === 'company' ? 'solid' : 'outline'" @click="evaluationType = 'company'" /></div></div></UCard><UCard><template #header><div class="flex items-center justify-between"><h2 class="text-lg font-semibold">{{ evaluationType === 'student' ? 'หัวข้อประเมินนักศึกษา' : 'หัวข้อประเมินสถานประกอบการ' }}</h2><UButton label="เพิ่มข้อคำถาม" icon="i-lucide-plus" size="xl" @click="add" /></div></template><div class="space-y-2"><div v-for="(q, i) in current" :key="q.id || i" class="flex items-center gap-2 rounded-lg border border-divider p-2"><span class="w-8 text-center text-muted">{{ i + 1 }}</span><UInput v-model="q.label" size="xl" class="flex-1" /><UButton icon="i-lucide-trash-2" color="error" variant="ghost" size="xl" aria-label="ลบข้อคำถาม" @click="remove(q)" /></div><UEmpty v-if="!current.length" title="ยังไม่มีข้อคำถาม" /></div><template #footer><div class="flex justify-end"><UButton label="บันทึกชุดคำถาม" icon="i-lucide-save" size="xl" :loading="saving" @click="save" /></div></template></UCard></div></template></UDashboardPanel></template>
